// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmTqbyWSDp9uKkK4FMCTRGYulqn-G5mYY',
    appId: '1:682498536167:web:67a273a7867e7117186842',
    messagingSenderId: '682498536167',
    projectId: 'eventhub-6cb95',
    authDomain: 'eventhub-6cb95.firebaseapp.com',
    storageBucket: 'eventhub-6cb95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo2lHt7t2EKzFSSbkoilF3c_8JcqxOen8',
    appId: '1:682498536167:android:d1919f2e9c2fdc9d186842',
    messagingSenderId: '682498536167',
    projectId: 'eventhub-6cb95',
    storageBucket: 'eventhub-6cb95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0rEPTJhmvhPUkUnJ7YLS5OGDIGqBHsw',
    appId: '1:682498536167:ios:950d7ae26c7bf8a7186842',
    messagingSenderId: '682498536167',
    projectId: 'eventhub-6cb95',
    storageBucket: 'eventhub-6cb95.firebasestorage.app',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0rEPTJhmvhPUkUnJ7YLS5OGDIGqBHsw',
    appId: '1:682498536167:ios:950d7ae26c7bf8a7186842',
    messagingSenderId: '682498536167',
    projectId: 'eventhub-6cb95',
    storageBucket: 'eventhub-6cb95.firebasestorage.app',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmTqbyWSDp9uKkK4FMCTRGYulqn-G5mYY',
    appId: '1:682498536167:web:3e5754eb85ea3c1e186842',
    messagingSenderId: '682498536167',
    projectId: 'eventhub-6cb95',
    authDomain: 'eventhub-6cb95.firebaseapp.com',
    storageBucket: 'eventhub-6cb95.firebasestorage.app',
  );
}
